version: '2'
services:
  php:
    container_name: craft_php
    image: yiisoftware/yii2-php:7.3-apache
    links:
      - mysql:mysql
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  mysql:
      container_name: craft_mysql
      restart: always
      image: mysql:5.7
      ports:
          - "33061:3306"
      environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=1
      volumes:
          - ./storage/database:/var/lib/mysql
