name: Craft Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Docker
      run: docker-compose up -d

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Create database
      run: mysql -h 127.0.0.1 -P 33061 -e "CREATE DATABASE craft;" -uroot

    - name: Run Unit Tests
      run: docker exec craft_php bash -c 'codecept run unit'
